# ┌─── 1. Typography & Theme ──────────────────────────────────────────────────┐

# [NOTE] Decouple colors to allow rapid theme switching via symlinks
include colors.conf

font_family      JetBrainsMono Nerd Font Mono
font_size        14.0

bold_font        auto
italic_font      auto
bold_italic_font auto


# ┌─── 2. Visuals & Interface ─────────────────────────────────────────────────┐

cursor_shape     block
cursor_blink_interval 0.5

# [NOTE] Motion trailing improves eye tracking during high-speed scrolling
cursor_trail     1

window_padding_width 10

# Disable intrusive interface elements
enable_audio_bell no
confirm_os_window_close 0


# ┌─── 3. Performance & Rendering ─────────────────────────────────────────────┐

# Minimize input-to-render latency
input_delay      0
repaint_delay    2

# [WARN] Bypassing V-Sync eliminates lag but may cause visual tearing
sync_to_monitor  no


# ┌─── 4. Scrollback & System Logic ───────────────────────────────────────────┐

scrollback_lines 10000
wheel_scroll_multiplier 3.0

# [FIX] Volatile pipe to treat terminal history as a temporary Neovim buffer
scrollback_pager nvim -c "set ft=man nonumber nolist showtabline=0 foldcolumn=0 laststatus=0" -c "autocmd TermOpen * startinsert" -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "

# [NOTE] Remote control is mandatory for external environment scripts (e.g., Pyre)
allow_remote_control yes
listen_on        unix:@mykitty


# ┌─── 5. Keybindings ─────────────────────────────────────────────────────────┐

# Clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Font scaling
map ctrl+shift+equal     change_font_size all +2.0
map ctrl+shift+plus      change_font_size all +2.0
map ctrl+shift+minus     change_font_size all -2.0
map ctrl+shift+backspace change_font_size all 0

# Advanced Kittens
map ctrl+shift+p kitten hints --type url
map ctrl+shift+f kitten hints --type path --program -
map ctrl+shift+u kitten unicode_input
map ctrl+shift+d kitten diff

# Terminal History
map ctrl+shift+h show_scrollback
