# =================================================================
#          Rules for the "Dual Pane" Layout
# =================================================================

# --- Thunar (Left Pane) ---
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.5), move ((monitor_w*0.06)) ((monitor_h*0.1)), match:class ^(thunar)$

# --- Yazi (Right Pane) ---
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.45), move ((monitor_w*0.42)) ((monitor_h*0.45)), match:title ^(fm-yazi)$
