# =================================================================
#           Rules for the Unified "Showcase" Layout
# =================================================================

# --- Fastfetch (Center) ---
windowrule = float on, size (monitor_w*0.55) (monitor_h*0.5), move ((monitor_w*0.225)) ((monitor_h*0.25)), match:title ^(fastfetch)$

# --- Clock (Top Center) ---
windowrule = float on, size (monitor_w*0.55) (monitor_h*0.18), move ((monitor_w*0.225)) ((monitor_h*0.05)), match:initial_title ^(tty-clock)$

# --- Cava (Bottom) ---
windowrule = float on, size (monitor_w*0.98) (monitor_h*0.22), move ((monitor_w*0.01)) ((monitor_h*0.77)), match:initial_title ^(cava)$

# --- Unimatrix (Left) ---
windowrule = float on, size (monitor_w*0.2) (monitor_h*0.7), move ((monitor_w*0.01)) ((monitor_h*0.05)), match:initial_title ^(unimatrix)$

# --- Pipes (Right) ---
windowrule = float on, size (monitor_w*0.2) (monitor_h*0.7), move ((monitor_w*0.79)) ((monitor_h*0.05)), match:initial_title ^(pipes)$
