[defaults]
format = "{name}  {time}\n"
time_format = "%M:%S"

# ================= ЦИКЛ 1 =================
[[sessions]]
id = "work1"  # <--- Уникальный ID
duration = "25m"
name = "󰄉"
command = "notify-send -u critical 'Work 1 Done' 'Take a break!'"

[[sessions]]
id = "rest1"
duration = "5m"
name = "󰅶"
command = "notify-send 'Break 1 Done' 'Back to work!'"

# ================= ЦИКЛ 2 =================
[[sessions]]
id = "work2"
duration = "25m"
name = "󰄉"
command = "notify-send -u critical 'Work 2 Done' 'Take a break!'"

[[sessions]]
id = "rest2"
duration = "5m"
name = "󰅶"
command = "notify-send 'Break 2 Done' 'Back to work!'"

# ================= ЦИКЛ 3 =================
[[sessions]]
id = "work3"
duration = "25m"
name = "󰄉"
command = "notify-send -u critical 'Work 3 Done' 'Take a break!'"

[[sessions]]
id = "rest3"
duration = "5m"
name = "󰅶"
command = "notify-send 'Break 3 Done' 'Back to work!'"

# ================= ЦИКЛ 4 =================
[[sessions]]
id = "work4"
duration = "25m"
name = "󰄉"
command = "notify-send -u critical 'Work 4 Done' 'Take a break!'"

[[sessions]]
id = "rest4"
duration = "5m"
name = "󰅶"
command = "notify-send 'Break 4 Done' 'Back to work!'"
