[tools]

# ┌─── 1. Core Toolchains ─────────────────────────────────────────────────────┐

# Use LTS to ensure maximum stability for production builds
node = "lts"

# [NOTE] Uncomment to enable global tracking for other runtimes
# go   = "latest"
# rust = "latest"


[settings]

# ┌─── 2. Engine & Behavior ───────────────────────────────────────────────────┐

# [WARN] Experimental features enabled for integrated Task Runner and Env Vars
experimental = true

# Bypass confirmation prompts during tool installations
yes = true

# Number of concurrent compilation threads for source builds
jobs = 4


# ┌─── 3. Compatibility & Interop ─────────────────────────────────────────────┐

# [NOTE] Enable parsing of legacy config files (.nvmrc, .tool-versions)
legacy_version_file = true


# ┌─── 4. Language Specifics ──────────────────────────────────────────────────┐

# [NOTE] Global packages to be installed with every new Python version
# python_default_packages_file = "~/.config/mise/default-python-packages"
